name: Deploy Fetch Function to Cloud Run

on:
  push:
    paths:
      - 'fetch_function/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker configuration
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fetch-function/fetch-function ./fetch_function
          docker push asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fetch-function/fetch-function

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fetch-function \
            --image=asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fetch-function/fetch-function \
            --platform=managed \
            --region=asia-northeast1 \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars=TABLE_ID=${{ secrets.FETCH_TABLE_ID }}
