name: Deploy Fetch Function (Docker)

on:
  push:
    paths:
      - 'fetch_function/**'
      - '.github/workflows/fetch_deploy.yml'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fetch-function ./fetch_function

    - name: Push image to Artifact Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fetch-function

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fetch-function \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fetch-function \
          --platform managed \
          --region asia-northeast1 \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --update-env-vars TABLE_ID=${{ secrets.FETCH_TABLE_ID }} \
          --allow-unauthenticated=false
