name: Deploy Notify Function (Docker)

on:
  push:
    paths:
      - 'notify_function/**'
      - '.github/workflows/notify_deploy.yml'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/notify-function ./notify_function

    - name: Push to Artifact Registry
      run: |
        gcloud auth configure-docker
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/notify-function

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy notify-function \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/notify-function \
          --platform managed \
          --region asia-northeast1 \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --update-env-vars TABLE_ID=${{ secrets.FETCH_TABLE_ID }},LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }},LINE_USER_ID=${{ secrets.LINE_USER_ID }} \
          --allow-unauthenticated=false
